package config

// Defaults returns a Config populated with sensible production defaults.
// SummaryConfig is then passed through ApplyL2OperatingMode so its numeric
// fields reflect the default "balanced" profile without forcing every
// caller to run the mode resolver themselves.
func Defaults() *Config {
	cfg := defaultsRaw()
	_ = ApplyL2OperatingMode(&cfg.Compression.Summary, cfg.Compression.Summary.Mode)
	return cfg
}

// defaultsRaw returns the pre-mode-applied defaults. Separated from Defaults
// so Load() can decode TOML over an unresolved shell and resolve the mode
// only after env overrides have been applied.
func defaultsRaw() *Config {
	return &Config{
		Proxy: ProxyConfig{
			ListenAddress: "127.0.0.1",
			ListenPort:    8990,
			IPv6:          false,
		},
		Upstream: UpstreamConfig{
			Anthropic:    ProviderUpstream{BaseURL: "https://api.anthropic.com"},
			OpenAI:       ProviderUpstream{BaseURL: "https://api.openai.com"},
			CodexChatGPT: ProviderUpstream{BaseURL: "https://chatgpt.com"},
		},
		Compression: CompressionConfig{
			Layer1Enabled:             true,
			Layer2Enabled:             true,
			Layer3Enabled:             true,
			SlidingWindow:             5,
			MinMessagesForCompression: 8,
			MinTokensForLayer2:                15000,
			Layer2LatencyBudgetMs:             0, // 0 = guard off (opt-in)
			Layer2LatencyProjectionMultiplier: 1.2,
			Layer2LatencyEMAAlpha:             0.2,
			StructureMinTokens:        500,
			StructureLanguages: []string{
				"go", "typescript", "javascript", "rust", "python",
				"c", "cpp", "java", "ruby", "shell",
			},
			DedupSimilarityThreshold: 0.85,
			MiniMax: MiniMaxConfig{
				BaseURL:                "https://api.minimax.io/v1",
				APIKeyEnv:              "MINIMAX_API_KEY",
				Model:                  "minimax-m2.7",
				Temperature:            0,
				MaxRetries:             3,
				ConnectTimeoutSeconds:  5,
				ResponseTimeoutSeconds: 30,
				RateLimitRPM:           10,
			},
			Summary: SummaryConfig{
				// Mode=balanced is the default operating profile. The
				// numeric fields stay zero so ApplyL2OperatingMode can
				// fill them from the profile without pretending they
				// were operator-set. TOML/env values override after.
				Mode: ModeBalanced,
			},
			Tuning: TuningConfig{
				IncrementalOverlapThreshold: 0.70,
				IncrementalStaircase: []StaircaseStep{
					{MsgCountLE: 60, Threshold: 0.70},
					{MsgCountLE: 120, Threshold: 0.55},
					{MsgCountLE: 1_000_000, Threshold: 0.40},
				},
				OverflowSlidingWindow:      2,
				OverflowTargetRatio:        0.10,
				StructureInWindow:          false,
				StructureInWindowMinTokens: 1500,
				LoopDetection:              false,
				StructurePreview:           true,
				DedupStaircase: []StaircaseStep{
					{MsgCountLE: 10, Threshold: 0.88},
					{MsgCountLE: 20, Threshold: 0.85},
					{MsgCountLE: 40, Threshold: 0.82},
					{MsgCountLE: 1_000_000, Threshold: 0.78},
				},
				ToolCompressor: ToolCompressorTuning{
					AggressiveAfterMultiplier: 2,
					GitModerateDiffLimit:      60,
					TestMaxFailureLines:       40,
				},
			},
		},
		Cache: CacheConfig{
			ResponseCacheMaxEntries:       100,
			ResponseCacheTTLSeconds:       300,
			SummaryRefreshIntervalSeconds: 1800,
		},
		Usage: UsageConfig{
			EstimatedPrefillSpeed: 50000,
		},
		Secrets: SecretsConfig{
			Mode:      "redact",
			Allowlist: []string{},
		},
		Analytics: AnalyticsConfig{
			Dashboard:               true,
			LogDir:                  "~/.slimference/analytics",
			DashboardRefreshSeconds: 2,
			GainUSDPerMillionTokens: 0,
		},
		Logging: LoggingConfig{
			Level:  "debug",
			Format: "json",
			File:   "~/.slimference/logs/slimference.jsonl",
		},
		Filter: FilterConfig{
			PassthroughMaxChars: 2000,
		},
		Hooks: HooksConfig{},
		Debug: DebugConfig{},
	}
}

// DefaultTOML returns the default config as a TOML string for `config init`.
func DefaultTOML() string {
	return `# Slimference Configuration
# Generated by: slimference config init

[proxy]
listen_address = "127.0.0.1"
listen_port = 8990
ipv6 = false

[upstream.anthropic]
base_url = "https://api.anthropic.com"

[upstream.openai]
base_url = "https://api.openai.com"

[compression]
layer1_enabled = true
layer2_enabled = true
layer3_enabled = true
sliding_window = 5
min_messages_for_compression = 8
min_tokens_for_layer2 = 15000
# T54: optional latency guard. Non-zero to activate. Skips L2 when
# EMA-based projection would exceed the budget (ms).
layer2_latency_budget_ms = 0
layer2_latency_projection_multiplier = 1.2
layer2_latency_ema_alpha = 0.2
structure_min_tokens = 500
structure_languages = ["go", "typescript", "javascript", "rust", "python", "c", "cpp", "java", "ruby", "shell"]
dedup_similarity_threshold = 0.85

[compression.minimax]
base_url = "https://api.minimax.io/v1"
api_key_env = "MINIMAX_API_KEY"
model = "minimax-m2.7"
temperature = 0
max_retries = 3
connect_timeout_seconds = 5
response_timeout_seconds = 30
rate_limit_rpm = 10

[compression.summary]
# Operating mode: strict | balanced | fast. Selecting a mode configures
# target_ratio / max_ratio / min_ratio / strict as a coherent bundle. Any
# numeric field explicitly set below still overrides the profile.
# Env override: SLIMFERENCE_L2_MODE.
mode = "balanced"
# Explicit overrides (optional; leave unset to inherit from mode).
# target_ratio = 0.20
# max_ratio = 0.40
# min_ratio = 0.05
# strict = true

[compression.tuning]
# Incremental-summary overlap threshold: if an existing summary covers at
# least this fraction of the compressible range, do an incremental update
# instead of a full rebuild. Used only when incremental_staircase is empty.
incremental_overlap_threshold = 0.70
# Aggressive sliding window used only when upstream reports a context
# overflow (spec+.md §17.4).
overflow_sliding_window = 2
# Aggressive summary target ratio for the overflow recover path.
overflow_target_ratio = 0.10

# Conversation-size-keyed staircase of incremental-overlap thresholds. The
# first step whose msg_count_le is >= the current conversation length wins.
# Long conversations benefit from a lower threshold: a full rebuild costs
# proportionally more work while incremental updates remain cheap.
[[compression.tuning.incremental_staircase]]
msg_count_le = 60
threshold = 0.70
[[compression.tuning.incremental_staircase]]
msg_count_le = 120
threshold = 0.55
[[compression.tuning.incremental_staircase]]
msg_count_le = 1000000
threshold = 0.40

# T24: allow Layer 1 structure extraction on large tool_result blocks even
# when they fall inside the sliding window. Conservative default: off.
# When enabled, only tool_result blocks above structure_in_window_min_tokens
# and not on the last message are eligible.
structure_in_window = false
structure_in_window_min_tokens = 1500

# T37: detect retry loops (>=4 consecutive user turns with >=0.75 Jaccard
# word similarity) and prepend a short nudge to the final user message so
# the model can break out. Default off.
loop_detection = false

# T38: replace large tool_result blocks (>=4 KB) with a shape-aware
# preview (JSON / paths / ASCII table) when strictly shorter. Default on
# (T55); set to false to restore the pre-2.1 pass-through behaviour.
structure_preview = true

[cache]
response_cache_max_entries = 100
response_cache_ttl_seconds = 300
summary_refresh_interval_seconds = 1800

[usage]
estimated_prefill_speed = 50000

[secrets]
mode = "redact"
# custom_patterns = [
#   { name = "My API Key", regex = "myapp-[a-z0-9]{32}" }
# ]
# allowlist = ["test/fixtures/**"]

[analytics]
dashboard = true
log_dir = "~/.slimference/analytics"
dashboard_refresh_seconds = 2
# Optional rough USD for slimference gain: savings_est_tokens / 1e6 * rate. Env: SLIMFERENCE_GAIN_USD_PER_MILLION
# gain_usd_per_million_tokens = 3.0

[logging]
level = "debug"
format = "json"
file = "~/.slimference/logs/slimference.jsonl"

# Layer 0 (slimference filter) — optional; SLIMFERENCE_FILTER_DB / SLIMFERENCE_TEE_DIR override when set.
[filter]
# Max characters (Unicode code points) of filtered stdout; 0 = unlimited. Env: SLIMFERENCE_FILTER_PASSTHROUGH_MAX_CHARS
passthrough_max_chars = 2000
# filter_db = "~/.slimference/filter.db"
# tee_dir = "~/.slimference/tee"
# Extra deny rules (RE2), matched against the full command line (after built-in destructive checks).
# deny_patterns = ['\\bnc\\s+-l\\s+']
#
# Per-project overrides (same deny_patterns key): .slimference/filters.toml in the working directory.

# Hook install (slimference hook install …) — optional path if "slimference" is not on PATH in the agent.
[hooks]
# slimference_command = "/usr/local/bin/slimference"

# Future: filter decision JSONL path (SLIMFERENCE_DEBUG_DECISIONS_LOG overrides).
[debug]
# decisions_log = "~/.slimference/decisions.jsonl"
`
}
